#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
svg_lib.py — shared design-system library for the K/OS "Operator Console"
GitHub profile assets.

Design system: original game-HUD visual language inspired by (never copying)
mission-dossier interfaces, XP bars and pixel accents. All colors, shapes and
icons are original.

Regenerate every asset with:  python3 scripts/build_assets.py [--photo photo.jpg]
Do not hand-edit the generated SVGs.
"""

import os

# ---------------------------------------------------------------------------
# DESIGN TOKENS
# ---------------------------------------------------------------------------

DARK = {
    "bg":        "#0A0E14",   # console chassis
    "panel":     "#0F1620",   # raised panel
    "panel2":    "#0C121A",   # recessed well
    "line":      "#1E2A38",   # hairline borders
    "line2":     "#2A3A4C",   # brighter border on hover-ish elements
    "text":      "#E6EDF3",   # primary text
    "muted":     "#8B98A9",   # secondary text
    "faint":     "#5A6675",   # tertiary / decorative text
    "green":     "#4ADE80",   # primary accent — money green / mission-passed
    "greenDim":  "#1E5C3A",   # filled XP segment edge / dim green
    "cyan":      "#22D3EE",   # secondary accent — telemetry
    "amber":     "#FBBF24",   # warning / pending XP
    "violet":    "#A78BFA",   # Q-Trust brand
    "red":       "#F87171",   # threat level only
    "black":     "#05070A",
}

LIGHT = {
    "bg":        "#F6F8FA",
    "panel":     "#FFFFFF",
    "panel2":    "#EDF1F5",
    "line":      "#D8DEE4",
    "line2":     "#C3CBD4",
    "text":      "#1F2328",
    "muted":     "#57606A",
    "faint":     "#8C959F",
    "green":     "#15803D",
    "greenDim":  "#BBF7D0",
    "cyan":      "#0E7490",
    "amber":     "#B45309",
    "violet":    "#6D28D9",
    "red":       "#B91C1C",
    "black":     "#24292F",
}

MONO = ("ui-monospace, 'Cascadia Mono', 'JetBrains Mono', Menlo, Consolas, "
        "'DejaVu Sans Mono', 'Liberation Mono', monospace")

BANNER_W = 1134      # hero width
BANNER_H = 396
STRIP_W  = 1134      # section console strip width
STRIP_H  = 54
MISSION_W = 1134     # mission dossier header width
MISSION_H = 148
ACH_W = 1134         # achievements strip
ACH_H = 150

GENERATED_BY = ("K/OS Operator Console asset — generated by scripts/build_assets.py "
                "— regenerate, never hand-edit")


def esc(s):
    """XML-escape text for SVG."""
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
             .replace('"', "&quot;"))


def _fmt(n):
    """Strip trailing zeros from floats for clean path data."""
    return f"{n:.2f}".rstrip("0").rstrip(".")


# ---------------------------------------------------------------------------
# PIXEL / HUD PRIMITIVES
# ---------------------------------------------------------------------------

def pixel_brackets(c, x, y, w, h, size=10, color=None, sw=2):
    """Four L-shaped corner brackets — the 'target lock' frame."""
    col = color or c["green"]
    g = size
    return f"""
  <path d="M {_fmt(x)} {_fmt(y+g)} V {_fmt(y)} H {_fmt(x+g)}" fill="none" stroke="{col}" stroke-width="{sw}"/>
  <path d="M {_fmt(x+w-g)} {_fmt(y)} H {_fmt(x+w)} V {_fmt(y+g)}" fill="none" stroke="{col}" stroke-width="{sw}"/>
  <path d="M {_fmt(x+w)} {_fmt(y+h-g)} V {_fmt(y+h)} H {_fmt(x+w-g)}" fill="none" stroke="{col}" stroke-width="{sw}"/>
  <path d="M {_fmt(x+g)} {_fmt(y+h)} H {_fmt(x)} V {_fmt(y+h-g)}" fill="none" stroke="{col}" stroke-width="{sw}"/>"""


def dither_strip(c, x, y, w, color, cell=4, rows=1, opacity="0.5"):
    """A row/rows of checkered 2px squares — restrained pixel accent."""
    rects = []
    for r in range(rows):
        for i in range(0, w, cell * 2):
            if i + cell <= w:
                rects.append(
                    f'<rect x="{_fmt(x+i)}" y="{_fmt(y+r*cell)}" width="{cell}" height="{cell}" fill="{color}"/>')
    body = "\n  ".join(rects)
    return f'\n  <g opacity="{opacity}">\n  {body}\n  </g>'


def blink_dot(c, x, y, r=4, color=None, dur="2.4s"):
    """Status LED with a soft SMIL pulse (GitHub-safe inside <img>)."""
    col = color or c["green"]
    return f"""
  <circle cx="{_fmt(x)}" cy="{_fmt(y)}" r="{r}" fill="{col}"/>
  <circle cx="{_fmt(x)}" cy="{_fmt(y)}" r="{r}" fill="{col}" opacity="0.25">
    <animate attributeName="r" values="{r};{r*2.4};{r}" dur="{dur}" repeatCount="indefinite"/>
    <animate attributeName="opacity" values="0.35;0;0.35" dur="{dur}" repeatCount="indefinite"/>
  </circle>"""


def caret(c, x, y, size=16, color=None, dur="1.1s"):
    """Blinking terminal cursor block."""
    col = color or c["green"]
    return f"""
  <rect x="{_fmt(x)}" y="{_fmt(y - size*0.8)}" width="{size*0.62:.0f}" height="{size}" fill="{col}">
    <animate attributeName="opacity" values="1;1;0;0;1" keyTimes="0;0.5;0.5;0.98;1" dur="{dur}" repeatCount="indefinite"/>
  </rect>"""


def glitch_title(c, x, y, text, size=30, weight=800, letter=2, fill=None,
                 ghost_dx=2.5, flicker="0s;1.8s;1.86s;1.92s;4s"):
    """Chromatic-aberration title: cyan + red ghosts flicker around white text.
    Ghosts are mostly invisible and flare briefly — GTA- cinematic, not noisy."""
    base = fill or c["text"]
    return f"""
  <g font-family="{MONO}" font-size="{size}" font-weight="{weight}" letter-spacing="{letter}">
    <text x="{_fmt(x+ghost_dx)}" y="{y}" fill="{c['cyan']}" opacity="0">{text}</text>
    <text x="{_fmt(x-ghost_dx)}" y="{_fmt(y+0.5)}" fill="{c['red']}" opacity="0">{text}</text>
    <text x="{x}" y="{y}" fill="{base}">{text}</text>
  </g>
  <g font-family="{MONO}" font-size="{size}" font-weight="{weight}" letter-spacing="{letter}">
    <text x="{_fmt(x+ghost_dx)}" y="{y}" fill="{c['cyan']}" opacity="0">
      {text}
      <animate attributeName="opacity" values="0;0;0.55;0;0" keyTimes="0;0.44;0.47;0.5;1" dur="5.2s" repeatCount="indefinite"/>
    </text>
    <text x="{_fmt(x-ghost_dx)}" y="{y}" fill="{c['red']}" opacity="0">
      {text}
      <animate attributeName="opacity" values="0;0;0.4;0;0" keyTimes="0;0.45;0.48;0.51;1" dur="5.2s" repeatCount="indefinite"/>
    </text>
  </g>"""


def scanlines(c, w, h, opacity="0.05", line=1.5, gap=3.5):
    """CRT scanline overlay pattern."""
    return f"""
  <defs>
    <pattern id="scan" width="4" height="{_fmt(line+gap)}" patternUnits="userSpaceOnUse">
      <rect width="4" height="{line}" fill="{c['black']}" opacity="0.9"/>
    </pattern>
  </defs>
  <rect width="{w}" height="{h}" fill="url(#scan)" opacity="{opacity}" pointer-events="none"/>"""


def chassis(c, w, h, rx=10, fill=None, stroke=None, sw=1):
    """The outer device body of a panel."""
    return (f'<rect x="0" y="0" width="{w}" height="{h}" rx="{rx}" '
            f'fill="{fill or c["bg"]}" stroke="{stroke or c["line"]}" stroke-width="{sw}"/>')


def mono(text_attrs="", fill="", content=""):
    return (f'<text font-family="{MONO}" {text_attrs} fill="{fill}">'
            f'{content}</text>')


# ---------------------------------------------------------------------------
# ASSET 1 — SECTION CONSOLE STRIPS  (under each markdown heading)
# ---------------------------------------------------------------------------

def section_strip(c, num, title, tag):
    """Full-width console strip: letterbox rules, section index, tag, caret.
    Rendered under a real markdown heading so text stays selectable."""
    W, H = STRIP_W, STRIP_H
    y_mid = H / 2 + 4
    bar_y = 8
    parts = []
    parts.append(chassis(c, W, H, rx=6))
    # GTA-style letterbox rules top and bottom
    parts.append(f'<rect x="0" y="{bar_y}" width="{W}" height="2" fill="{c["green"]}" opacity="0.75"/>')
    parts.append(f'<rect x="0" y="{H-bar_y-2}" width="{W}" height="2" fill="{c["line2"]}"/>')
    # left index block
    parts.append(f'<rect x="18" y="{_fmt(H/2-13)}" width="52" height="26" rx="4" fill="{c["panel2"]}" stroke="{c["line"]}"/>')
    parts.append(mono(f'x="44" y="{_fmt(y_mid)}" font-size="13" font-weight="700" text-anchor="middle" letter-spacing="1"',
                      c["green"], f"//{num}"))
    # title echo (decorative; real text lives in the markdown heading)
    parts.append(mono(f'x="88" y="{_fmt(y_mid)}" font-size="13" font-weight="700" letter-spacing="3.5"',
                      c["text"], esc(title.upper())))
    # tag chip right
    tw = 8 * len(tag) + 34
    parts.append(f'<rect x="{W-tw-52}" y="{_fmt(H/2-11)}" width="{tw}" height="22" rx="11" fill="{c["panel2"]}" stroke="{c["line"]}"/>')
    parts.append(mono(f'x="{W-52-tw/2}" y="{_fmt(y_mid)}" font-size="11" letter-spacing="1" text-anchor="middle"',
                      c["muted"], esc(tag)))
    parts.append(caret(c, W - 34, y_mid + 1, size=13, color=c["green"]))
    # tick ruler + circuit trace
    parts.append(dither_strip(c, 88, H - 16, min(320, W // 3), c["line2"], cell=3, rows=1, opacity="0.6"))
    parts.append(f'<path d="M {88 + min(340, W // 3)} {_fmt(H/2)} H {_fmt(W - tw - 70)}" stroke="{c["line"]}" stroke-width="1" stroke-dasharray="6 5" opacity="0.9"/>')
    parts.append(f'<circle cx="{_fmt(88 + min(340, W // 3))}" cy="{_fmt(H/2)}" r="2.2" fill="{c["green"]}"/>')
    # corner "screws" — pixel squares anchoring the chassis
    for sx_, sy_ in [(12, 12), (W - 16, 12), (12, H - 16), (W - 16, H - 16)]:
        parts.append(f'<rect x="{sx_}" y="{sy_}" width="4" height="4" fill="{c["line2"]}"/>')
    body = "\n".join(parts)
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="{esc(tag)}">
<!-- {GENERATED_BY} -->
{body}
</svg>
"""
    return svg


# ---------------------------------------------------------------------------
# ASSET 2 — MISSION DOSSIER HEADER  (one per flagship repo)
# ---------------------------------------------------------------------------

def mission_card(c, idx, title, subtitle, status, version, threat, proof, pips, accent=None):
    """GTA-mission-dossier-style header card. Evidence table lives in markdown below."""
    acc = accent or c["green"]
    W, H = MISSION_W, MISSION_H
    parts = []
    parts.append(chassis(c, W, H, rx=8))
    # cinematic letterbox bars
    parts.append(f'<rect x="0" y="0" width="{W}" height="10" fill="{c["black"]}"/>')
    parts.append(f'<rect x="0" y="0" width="{W}" height="3" fill="{acc}" opacity="0.8"/>')
    parts.append(f'<rect x="0" y="{H-10}" width="{W}" height="10" fill="{c["black"]}"/>')
    parts.append(f'<rect x="0" y="{H-3}" width="{W}" height="3" fill="{acc}" opacity="0.35"/>')

    # mission index + title
    parts.append(mono(f'x="36" y="52" font-size="14" font-weight="700" letter-spacing="4"', c["muted"], f"MISSION {idx:02d}"))
    parts.append(f'<g font-family="{MONO}" font-size="34" font-weight="800" letter-spacing="1.5"><text x="36" y="92" fill="{c["text"]}">{esc(title)}</text></g>')
    parts.append(mono(f'x="38" y="118" font-size="13" letter-spacing="0.4"', c["muted"], esc(subtitle)))

    # status block, right side
    sx = W - 316
    parts.append(f'<rect x="{sx}" y="30" width="280" height="88" rx="6" fill="{c["panel2"]}" stroke="{c["line"]}"/>')
    parts.append(blink_dot(c, sx + 24, 52, r=4, color=acc, dur="2.2s"))
    parts.append(mono(f'x="{sx+40}" y="56" font-size="12" font-weight="700" letter-spacing="2"', acc, f"STATUS · {esc(status)}"))
    parts.append(mono(f'x="{sx+20}" y="80" font-size="11.5" letter-spacing="1.5"', c["muted"], f"PATCH {esc(version)}"))
    # difficulty pips
    px = sx + 20
    for i in range(5):
        filled = i < pips
        col = acc if filled else c["line2"]
        parts.append(f'<rect x="{px + i*24}" y="92" width="17" height="7" rx="1" fill="{col}" opacity="{1 if filled else 0.55}"/>')
    parts.append(mono(f'x="{px+5*24+10}" y="99" font-size="9.5" letter-spacing="1.2"', c["faint"], "DIFFICULTY"))

    # bottom telemetry line
    parts.append(mono(f'x="36" y="{H-20}" font-size="11.5" letter-spacing="0.5"', c["faint"],
                      f"THREAT: {esc(threat)}   ·   PROOF: {esc(proof)}"))
    # depth: soft top glow under the letterbox bar
    parts.append(f'<rect x="0" y="10" width="{W}" height="26" fill="{acc}" opacity="0.05"/>')
    parts.append(scanlines(c, W, H, opacity="0.06"))
    body = "\n".join(p for p in parts if p.strip())
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="Mission {idx:02d}: {esc(title)} — {esc(subtitle)}. Status {esc(status)}, patch {esc(version)}.">
<!-- {GENERATED_BY} -->
{body}
</svg>
"""
    return svg


# ---------------------------------------------------------------------------
# ASSET 3 — ACHIEVEMENTS STRIP  (verified unlocks only)
# ---------------------------------------------------------------------------

def _hex_badge(c, cx, cy, r, color, title, sub, pulse=False):
    pts = " ".join(f"{_fmt(cx + r*_cos(60*i-30))},{_fmt(cy - r*_sin(60*i-30))}" for i in range(6))
    ring = f'<polygon points="{pts}" fill="{c["panel2"]}" stroke="{color}" stroke-width="2"/>'
    inner = f'<polygon points="{pts}" fill="none" stroke="{color}" stroke-width="1" opacity="0.35" transform="translate({_fmt(cx)} {_fmt(cy)}) scale(0.78) translate({_fmt(-cx)} {_fmt(-cy)})"/>'
    anim = ""
    if pulse:
        anim = (f'<polygon points="{pts}" fill="{color}" opacity="0">'
                f'<animate attributeName="opacity" values="0;0.18;0" dur="3s" repeatCount="indefinite"/>'
                f'</polygon>')
    txt = (mono(f'x="{_fmt(cx)}" y="{_fmt(cy + r + 26)}" font-size="11.5" font-weight="700" letter-spacing="0.6" text-anchor="middle"', c["text"], esc(title))
           + mono(f'x="{_fmt(cx)}" y="{_fmt(cy + r + 42)}" font-size="10" text-anchor="middle"', c["muted"], esc(sub)))
    return f"  {ring}\n  {inner}\n  {anim}\n  {txt}"


def _cos(deg):
    import math
    return math.cos(math.radians(deg))


def _sin(deg):
    import math
    return math.sin(math.radians(deg))


def achievements_strip(c, items, pulse_last=True):
    """Row of hexagonal achievement emblems. items: (title, sub, color, icon_svg)."""
    W, H = ACH_W, ACH_H
    n = len(items)
    parts = [chassis(c, W, H, rx=8)]
    parts.append(f'<rect x="0" y="0" width="{W}" height="3" fill="{c["amber"]}" opacity="0.55"/>')
    # caption left
    parts.append(mono(f'x="28" y="{_fmt(H/2-6)}" font-size="12" font-weight="700" letter-spacing="2"', c["amber"], "UNLOCKED"))
    parts.append(mono(f'x="28" y="{_fmt(H/2+14)}" font-size="10.5"', c["faint"], "receipt-checked"))
    parts.append(mono(f'x="28" y="{_fmt(H/2+29)}" font-size="10.5"', c["faint"], "no vanity unlocks"))
    # vertical divider
    parts.append(f'<rect x="150" y="24" width="1" height="{H-48}" fill="{c["line"]}"/>')
    # connecting circuit trace behind the badges
    parts.append(f'<path d="M 178 {_fmt(H/2-12)} H {_fmt(W-22)}" stroke="{c["line"]}" stroke-width="1" stroke-dasharray="3 6" opacity="0.8"/>')
    # badges
    span = W - 170 - 20
    step = span / n
    for i, (title, sub, color, icon) in enumerate(items):
        cx = 170 + step * (i + 0.5)
        cy = H / 2 - 12
        pulse = pulse_last and i == n - 1
        parts.append(_hex_badge(c, cx, cy, 26, color, title, sub, pulse=pulse))
        if icon:
            parts.append(icon(cx, cy, color))
    parts.append(scanlines(c, W, H, opacity="0.05"))
    body = "\n".join(parts)
    svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}" role="img" aria-label="Achievements unlocked: {esc('; '.join(i[0] for i in items))} — all verifiable from repository history.">
<!-- {GENERATED_BY} -->
{body}
</svg>
"""
    return svg


# --- tiny original vector icons for the badges (no emoji, no copied art) ---

def icon_fork(cx, cy, color):
    return f"""<g stroke="{color}" stroke-width="2.4" fill="none" stroke-linecap="round">
  <circle cx="{_fmt(cx-9)}" cy="{_fmt(cy-8)}" r="3.6"/>
  <circle cx="{_fmt(cx+9)}" cy="{_fmt(cy-8)}" r="3.6"/>
  <circle cx="{cx}" cy="{_fmt(cy+9)}" r="3.6"/>
  <path d="M {_fmt(cx-9)} {_fmt(cy-4)} V {_fmt(cy+1)} q 0 4 4 4 h 10"/>
  <path d="M {_fmt(cx+9)} {_fmt(cy-4)} V {_fmt(cy+1)}"/>
</g>"""


def icon_shield(cx, cy, color):
    return f"""<g stroke="{color}" stroke-width="2.4" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path d="M {_fmt(cx)} {_fmt(cy-11)} l 9 4 v 7 c 0 6 -4 9 -9 11 c -5 -2 -9 -5 -9 -11 v -7 z"/>
  <path d="M {_fmt(cx-4)} {_fmt(cy)} l 3 3 l 6 -6"/>
</g>"""


def icon_selfscan(cx, cy, color):
    """A scanner looking at itself: two brackets + center dot radar."""
    return f"""<g stroke="{color}" stroke-width="2.4" fill="none" stroke-linecap="round">
  <path d="M {_fmt(cx-11)} {_fmt(cy-5)} v -4 h 4"/>
  <path d="M {_fmt(cx+7)} {_fmt(cy-9)} h 4 v 4"/>
  <path d="M {_fmt(cx+11)} {_fmt(cy+5)} v 4 h -4"/>
  <path d="M {_fmt(cx-7)} {_fmt(cy+9)} h -4 v -4"/>
  <circle cx="{cx}" cy="{cy}" r="3" fill="{color}" stroke="none">
    <animate attributeName="opacity" values="1;0.25;1" dur="2s" repeatCount="indefinite"/>
  </circle>
</g>"""


def icon_race(cx, cy, color):
    """Two lanes, one winner: parallel bars with diverging outcome."""
    return f"""<g stroke="{color}" stroke-width="2.6" fill="none" stroke-linecap="round">
  <path d="M {_fmt(cx-12)} {_fmt(cy-6)} h 14"/>
  <path d="M {_fmt(cx-12)} {_fmt(cy+3)} h 20" opacity="0.45"/>
  <path d="M {_fmt(cx+6)} {_fmt(cy-6)} l 5 -1"/>
  <path d="M {_fmt(cx+4)} {_fmt(cy+3)} h 8" stroke-dasharray="2 3"/>
  <circle cx="{_fmt(cx+9)}" cy="{_fmt(cy-7)}" r="2.2" fill="{color}" stroke="none"/>
</g>"""


def icon_gauge(cx, cy, color):
    return f"""<g stroke="{color}" stroke-width="2.4" fill="none" stroke-linecap="round">
  <path d="M {_fmt(cx-10)} {_fmt(cy+6)} a 10 10 0 0 1 20 0"/>
  <path d="M {_fmt(cx)} {_fmt(cy+6)} l 5 -7" stroke="{color}"/>
  <circle cx="{cx}" cy="{_fmt(cy+6)}" r="1.8" fill="{color}" stroke="none"/>
</g>"""
